name: delivery-review
version: "1.0.0"
description: Release readiness and risk assessment

triggers:
  manual:
    command: /delivery-review
    description: Assess release readiness and identify risks

  suggested:
    - when: "Sprint ending soon"
    - when: "Release branch created"
    - when: "Multiple PRs ready for release"

tools_required:
  - github
  - jira

output:
  - type: markdown
    filename: release_readiness.md
  - type: jira_comment
    optional: true
    description: Add readiness report to release ticket

config:
  include_test_coverage: true
  include_dependency_check: true
  risk_threshold: medium
