name: portfolio-insights
version: "1.0.0"
description: Portfolio and delivery metrics analysis

triggers:
  manual:
    command: /portfolio-insights
    description: Generate portfolio insights and delivery metrics

  suggested:
    - when: "Quarterly planning"
    - when: "Roadmap review"
    - when: "Capacity planning"

tools_required:
  - jira
  - confluence

output:
  - type: markdown
    filename: portfolio_insights.md
  - type: confluence_page
    optional: true
    description: Publish to Confluence

config:
  include_velocity: true
  include_roadmap: true
  include_tech_debt: true
  time_range_months: 3
